stu.exe: student.o menu.o main.o
	gcc -o stu student.o menu.o main.o 
student.o: student.c
	gcc -o student.o -c student.c
menu.o: menu.c
	gcc -o menu.o -c menu.c
main.o: main.c
	gcc -o main.o -c main.c
